# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: false
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: false
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    app.monolog_web_processor:
        class: Symfony\Bridge\Monolog\Logger
        arguments:
            - 'monolog.logger'
            - 'file_log'

    #фабрика сервиса вк
    app.vk_service_factory:
        class: getjump\Vk\Core
        calls:
            - method: 'apiVersion'
              arguments: ['5.5']

    #сервис фотографий
    app.photo_service:
        class: AppBundle\Service\PhotoService
        arguments:
            - '@app.vk_service_factory'
            - '@doctrine.orm.entity_manager'

    #Сервис стены
    app.wall_service:
        class: AppBundle\Service\WallService
        arguments:
            - '@app.photo_service'
            - '@doctrine.orm.entity_manager'

    #Комманда парсинга стены
    app.wall_parse:
        class: AppBundle\Command\WallParse
        arguments:
            - '@app.wall_service'
            - '@app.vk_service_factory'
            - '@doctrine.orm.entity_manager'
        tags:
            - console.command

    #комманда загрузки фотографий
    app.upload_photo:
        class: AppBundle\Command\UploadPhoto
        arguments:
            - '@app.photo_service'
            - '@app.vk_service_factory'

        tags:
            -  { name: console.command }

    #комманда создание записей
    app.create_post:
        class: AppBundle\Command\CreatePost
        arguments:
            - '@app.vk_service_factory'
            - '@doctrine.orm.entity_manager'
            - '@app.photo_service'
            - '@app.wall_service'
            - '@logger'
        tags:
            -  { name: console.command }

    #Worker
    app.worker:
        class: AppBundle\Command\Worker
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            -  { name: console.command }